import { Product, Store, Coach, Athlete, NewsArticle, CommunityPost } from './types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-1',
    owner_id: 'seller-pro-1',
    name: 'Motiom Pro Lab',
    slug: 'motiom-pro-lab',
    description: 'Laboratório e boutique oficial de equipamentos esportivos de alta performance, vestuário técnico de compressão e calçados para maratonistas e triatletas.',
    logo_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=1200&q=80',
    category: 'Alta Performance',
    is_verified: true,
    verification_status: 'verified',
    verification_requested_at: '2026-01-15T10:00:00Z',
    verification_docs: {
      cnpj: '48.912.834/0001-92',
      company_name: 'Motiom Pro Lab Equipamentos Esportivos Ltda',
      website: 'https://coremotiom.com/stores/motiom-pro-lab',
    },
    contact_email: 'contato@motiompro.com.br',
    contact_phone: '+55 (11) 98822-1049',
    location: 'São Paulo, SP',
    rating: 4.95,
    sales_count: 842,
    products_count: 18,
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'store-2',
    owner_id: 'seller-pro-2',
    name: 'AeroTrack Dynamics',
    slug: 'aerotrack-dynamics',
    description: 'Especialistas em ciclismo de estrada, contra-relógio e componentes aerodinâmicos de carbono certificados para atletas de elite.',
    logo_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1200&q=80',
    category: 'Ciclismo & Triatlo',
    is_verified: true,
    verification_status: 'verified',
    verification_requested_at: '2026-02-01T14:30:00Z',
    verification_docs: {
      cnpj: '32.145.890/0001-11',
      company_name: 'AeroTrack Dynamics Brasil Comércio de Artigos Esportivos',
      website: 'https://aerotrack.com.br',
    },
    contact_email: 'suporte@aerotrack.com.br',
    contact_phone: '+55 (41) 99123-4567',
    location: 'Curitiba, PR',
    rating: 4.88,
    sales_count: 415,
    products_count: 12,
    created_at: '2026-01-20T09:00:00Z',
  },
  {
    id: 'store-3',
    owner_id: 'seller-pro-3',
    name: 'Vortex Endurance Store',
    slug: 'vortex-endurance',
    description: 'Roupas técnicas, coletes de hidratação e tecnologia vestível para trail running, montanha e ultramaratonas.',
    logo_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80',
    category: 'Trail & Outdoor',
    is_verified: true,
    verification_status: 'verified',
    verification_requested_at: '2026-02-10T11:00:00Z',
    verification_docs: {
      cnpj: '19.482.001/0001-44',
      company_name: 'Vortex Outdoor Equipamentos Esportivos',
    },
    contact_email: 'vendas@vortexendurance.com',
    location: 'Belo Horizonte, MG',
    rating: 4.92,
    sales_count: 290,
    products_count: 9,
    created_at: '2026-02-05T12:00:00Z',
  },
  {
    id: 'store-4',
    owner_id: 'seller-pro-4',
    name: 'Pulse Peak Tech',
    slug: 'pulse-peak-tech',
    description: 'Monitores cardíacos de precisão, sensores de cadência e wearables avançados para biohacking e recuperação muscular.',
    logo_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1510519138111-5778a0ff28ac?w=1200&q=80',
    category: 'Tecnologia & Wearables',
    is_verified: false,
    verification_status: 'pending',
    verification_requested_at: '2026-08-25T16:00:00Z',
    contact_email: 'atendimento@pulsepeak.com',
    location: 'Florianópolis, SC',
    rating: 4.70,
    sales_count: 64,
    products_count: 5,
    created_at: '2026-07-15T15:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // B2C Products (Official Stores)
  {
    id: 'prod-b2c-1',
    title: 'Tênis Carbon Pace Elite V4',
    description: 'Placa integral de fibra de carbono curvada com espuma nitrogenada de alto retorno elástico. Projetado para recordes pessoais em provas de 10k, meia maratona e maratona completa. Peso: 198g (tam 41). Drop: 8mm.',
    price: 1399.90,
    original_price: 1599.90,
    category: 'Calçados',
    sport: 'Corrida',
    condition: 'novo',
    product_type: 'b2c',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    ],
    seller_id: 'seller-pro-1',
    seller_name: 'Motiom Pro Lab',
    seller_avatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&q=80',
    store_id: 'store-1',
    store_name: 'Motiom Pro Lab',
    is_verified_store: true,
    stock: 14,
    views: 3420,
    likes_count: 245,
    location: 'São Paulo, SP',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-10T10:00:00Z',
    brand: 'Motiom Racing',
    rating: 4.9,
    reviews_count: 38,
    tags: ['Placa de Carbono', 'Maratona', 'Super Tênis', 'Lançamento'],
  },
  {
    id: 'prod-b2c-2',
    title: 'Macaquinho de Triatlo AeroSpeed Pro Carbon',
    description: 'Tecido aerodinâmico com caneluras texturizadas nos ombros e mangas para redução de arrasto no ciclismo. Forro italiano de densidade gradual de secagem ultra-rápida na natação e corrida.',
    price: 890.00,
    original_price: 980.00,
    category: 'Roupas',
    sport: 'Triatlo',
    condition: 'novo',
    product_type: 'b2c',
    images: [
      'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&q=80',
      'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80',
    ],
    seller_id: 'seller-pro-2',
    seller_name: 'AeroTrack Dynamics',
    seller_avatar: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=200&q=80',
    store_id: 'store-2',
    store_name: 'AeroTrack Dynamics',
    is_verified_store: true,
    stock: 8,
    views: 1280,
    likes_count: 112,
    location: 'Curitiba, PR',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-15T14:20:00Z',
    brand: 'AeroTrack',
    rating: 4.95,
    reviews_count: 22,
    tags: ['Triatlo', 'Aerodinâmico', 'Ironman Ready'],
  },
  {
    id: 'prod-b2c-3',
    title: 'Colete de Hidratação Alpine Trail 12L + 2 Soft Flasks',
    description: 'Estrutura ergonômica sem pontos de fricção com capacidade total de 12 litros e fixação para bastões de caminhada. Acompanha 2 soft flasks de 500ml com válvula de alto fluxo.',
    price: 649.00,
    original_price: 720.00,
    category: 'Equipamentos',
    sport: 'Trail Running',
    condition: 'novo',
    product_type: 'b2c',
    images: [
      'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    ],
    seller_id: 'seller-pro-3',
    seller_name: 'Vortex Endurance Store',
    seller_avatar: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=80',
    store_id: 'store-3',
    store_name: 'Vortex Endurance Store',
    is_verified_store: true,
    stock: 20,
    views: 940,
    likes_count: 88,
    location: 'Belo Horizonte, MG',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-18T09:10:00Z',
    brand: 'Vortex',
    rating: 4.8,
    reviews_count: 19,
    tags: ['Ultra Trail', 'Hidratação', 'Montanha'],
  },
  {
    id: 'prod-b2c-4',
    title: 'Monitor Cardíaco Óptico de Braço PulseTech BioSense',
    description: 'Sensor de ECG óptico com 6 diodos de alta precisão, conectividade dupla ANT+ e Bluetooth 5.3 com memória interna de 40 horas de treino. Bateria para 30 horas contínuas.',
    price: 499.00,
    category: 'Tecnologia & Wearables',
    sport: 'Corrida',
    condition: 'novo',
    product_type: 'b2c',
    images: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80',
      'https://images.unsplash.com/photo-1510519138111-5778a0ff28ac?w=800&q=80',
    ],
    seller_id: 'seller-pro-4',
    seller_name: 'Pulse Peak Tech',
    seller_avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200&q=80',
    store_id: 'store-4',
    store_name: 'Pulse Peak Tech',
    is_verified_store: false,
    stock: 15,
    views: 820,
    likes_count: 67,
    location: 'Florianópolis, SC',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-20T11:00:00Z',
    brand: 'PulseTech',
    rating: 4.7,
    reviews_count: 14,
    tags: ['Wearable', 'Biohacking', 'Cardio'],
  },

  // C2C Products (User to User Sales)
  {
    id: 'prod-c2c-1',
    title: 'Tênis de Corrida AlphaFly Next% 2 (Usado 45km)',
    description: 'Tênis utilizado exclusivamente em 2 provas de 21k e um treino longo. Solado com desgaste mínimo (< 5%), cápsulas de Zoom Air 100% íntegras. Tamanho 42 BR. Acompanha caixa original.',
    price: 850.00,
    original_price: 2199.00,
    category: 'Calçados',
    sport: 'Corrida',
    condition: 'como_novo',
    product_type: 'c2c',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    ],
    seller_id: 'user-c2c-1',
    seller_name: 'Carlos Eduardo Ramos',
    seller_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    stock: 1,
    views: 2100,
    likes_count: 94,
    location: 'Campinas, SP',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-22T16:45:00Z',
    brand: 'Nike',
    tags: ['Venda Direta', '42 BR', 'Carbono'],
  },
  {
    id: 'prod-c2c-2',
    title: 'Ciclocomputador GPS Garmin Edge 530 + Suporte Frontal',
    description: 'Aparelho em excelente estado estético e operacional. Bateria com autonomia de mais de 16 horas. Sem riscos na tela (película de vidro aplicada desde o primeiro dia). Motivo da venda: upgrade para Edge 1040.',
    price: 1100.00,
    original_price: 2400.00,
    category: 'Tecnologia & Wearables',
    sport: 'Ciclismo',
    condition: 'usado_excelente',
    product_type: 'c2c',
    images: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80',
      'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&q=80',
    ],
    seller_id: 'user-c2c-2',
    seller_name: 'Juliana Vasconcelos',
    seller_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80',
    stock: 1,
    views: 1450,
    likes_count: 82,
    location: 'Ribeirão Preto, SP',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-26T10:15:00Z',
    brand: 'Garmin',
    tags: ['GPS', 'Strava Live', 'Película'],
  },
  {
    id: 'prod-c2c-3',
    title: 'Quadro Road Carbono Disc Tamanho 54cm',
    description: 'Quadro em carbono Toray T800 compatível com freios a disco Flat Mount e eixos passantes 12x142mm / 12x100mm. Acompanha garfo carbono, canote e movimento central Shimano.',
    price: 3200.00,
    original_price: 5800.00,
    category: 'Equipamentos',
    sport: 'Ciclismo',
    condition: 'usado_excelente',
    product_type: 'c2c',
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    ],
    seller_id: 'user-c2c-3',
    seller_name: 'Felipe Martins',
    seller_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    stock: 1,
    views: 890,
    likes_count: 51,
    location: 'Porto Alegre, RS',
    shipping_available: true,
    status: 'active',
    created_at: '2026-08-28T19:00:00Z',
    brand: 'Trek / Emonda',
    tags: ['54cm', 'Disc Brake', 'Carbono'],
  },
  {
    id: 'prod-c2c-4',
    title: 'Kettlebell de Competição 24kg em Aço Maciço',
    description: 'Padrão olímpico de competição com alça de 33mm em aço sem verniz para melhor aderência de magnésio. Cor verde oficial. Sem amassados ou ferrugem.',
    price: 310.00,
    original_price: 490.00,
    category: 'Equipamentos',
    sport: 'Crossfit & Funcional',
    condition: 'usado_bom',
    product_type: 'c2c',
    images: [
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    ],
    seller_id: 'user-c2c-4',
    seller_name: 'Rodrigo Brandão',
    seller_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    stock: 1,
    views: 520,
    likes_count: 29,
    location: 'Rio de Janeiro, RJ',
    shipping_available: false, // retirada em mãos
    status: 'active',
    created_at: '2026-08-29T14:10:00Z',
    brand: 'Rogue Fitness',
    tags: ['24kg', 'Competição', 'Retirada RJ'],
  },
];

export const INITIAL_COACHES: Coach[] = [
  {
    id: 'coach-1',
    name: 'Prof. Marcelo Albuquerque',
    title: 'Treinador de Alto Rendimento & Fisiologista do Exercício',
    specialty: 'Maratona & Corrida de Rua',
    sports: ['Corrida', 'Meia Maratona', 'Maratona'],
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    bio: 'Mais de 14 anos treinando atletas amadores rumo ao índice de Boston e sub-3h na maratona. Mestre em Fisiologia do Exercício pela USP e treinador certificado World Athletics Nível II.',
    rating: 4.98,
    reviews_count: 54,
    hourly_rate: 280.00,
    location: 'São Paulo, SP (Presencial / Online)',
    is_certified: true,
    cref_number: 'CREF 049812-G/SP',
    availability: 'Terças e Quintas (Manhã / Noite) e Consultoria Online',
  },
  {
    id: 'coach-2',
    name: 'Dra. Camila Nogueira',
    title: 'Especialista em Triatlo & Biomecânica do Ciclismo',
    specialty: 'Triatlo & Bike Fit Dinâmico',
    sports: ['Triatlo', 'Ciclismo', 'Natação'],
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    bio: 'Treinadora Nível 2 Ironman Certified. Análise de potência de pedalada, periodização fisiológica e técnica eficiente de natação em águas abertas.',
    rating: 4.94,
    reviews_count: 39,
    hourly_rate: 320.00,
    location: 'Florianópolis, SC (Online Global)',
    is_certified: true,
    cref_number: 'CREF 031984-G/SC',
    availability: 'Planilhas semanais no TrainingPeaks com feedback por vídeo',
  },
  {
    id: 'coach-3',
    name: 'Lucas Barreto',
    title: 'Head Coach de Trail Running & Condicionamento em Altitude',
    specialty: 'Ultra Trail & Montanha',
    sports: ['Trail Running', 'Skyrunning', 'Caminhada'],
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    bio: 'Atleta com 6 conclusões de provas de 100km e treinador de atletas para UTMB, KTR e Endurance series. Foco em força excêntrica e descidas técnicas.',
    rating: 4.89,
    reviews_count: 27,
    hourly_rate: 220.00,
    location: 'Campos do Jordão, SP',
    is_certified: true,
    cref_number: 'CREF 089123-G/SP',
    availability: 'Treinos de campo mensais e periodização individualizada',
  },
];

export const INITIAL_ATHLETES: Athlete[] = [
  {
    id: 'athlete-1',
    name: 'Beatriz Zanetti',
    sport: 'Corrida de Rua & Maratona',
    category: 'Elite Sub-25 (PB 2h39m Maratona)',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80',
    bio: 'Maratonista brasileira em preparação para os Jogos Pan-Americanos. Campeã da Maratona de Porto Alegre 2025.',
    achievements: [
      'Campeã Maratona de Porto Alegre 2025',
      'Top 3 Meia Maratona Internacional de SP',
      'Recorde Pessoal 2h39m18s',
    ],
    location: 'Curitiba, PR',
    sponsorship_status: 'seeking',
    instagram: '@beatriz_running',
  },
  {
    id: 'athlete-2',
    name: 'Gabriel Fonseca',
    sport: 'Ciclismo de Estrada & Contra-Relógio',
    category: 'Elite Masculino',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    bio: 'Ciclista profissional especialista em provas de contrarrelógio e percursos com altimetria agressiva. Atleta patrocinado pela AeroTrack.',
    achievements: [
      'Bicampeão Brasileiro de Contrarrelógio Sub-23',
      'Vencedor de Etapa no Tour do Rio',
      'Potência FTP: 410W',
    ],
    location: 'Belo Horizonte, MG',
    sponsorship_status: 'sponsored',
    instagram: '@gabrielfonseca_tt',
  },
];

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    author_id: 'user-c2c-1',
    author_name: 'Carlos Eduardo Ramos',
    author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    author_badge: 'Maratonista Sub-3h',
    category: 'treino',
    title: 'Longão de 32km com ritmo progressivo: análise de cadência e hidratação',
    content: 'Hoje foi dia do último treino longo chave antes da maratona. Comecei os primeiros 10km em Z2 (4:45/km), passei para ritmo de prova (4:12/km) dos 10 ao 28km e fechei os últimos 4km em 3:55/km. Consumi 75g de carboidrato por hora com géis de maltodextrina + frutose. Como vocês dividem a nutrição intra-treino em dias quentes?',
    image_url: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80',
    likes_count: 46,
    comments_count: 6,
    comments: [
      {
        id: 'comm-1',
        author_name: 'Prof. Marcelo Albuquerque',
        author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
        content: 'Excelente controle de ritmo Carlos! 75g/h é uma janela segura para evitar desconforto gástrico. Mantenha essa mesma proporção no dia da prova.',
        created_at: '2026-08-30T11:20:00Z',
      },
      {
        id: 'comm-2',
        author_name: 'Juliana Vasconcelos',
        author_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&q=80',
        content: 'Baita ritmo! Qual tênis você usou nesse treino longo?',
        created_at: '2026-08-30T12:05:00Z',
      }
    ],
    created_at: '2026-08-30T09:30:00Z',
  },
  {
    id: 'post-2',
    author_id: 'seller-pro-1',
    author_name: 'Motiom Pro Lab',
    author_avatar: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&q=80',
    author_badge: 'Loja Oficial ✓',
    category: 'equipamento',
    title: 'Guia Técnico: Como avaliar o desgaste da placa de carbono em calçados de competição',
    content: 'Muitos atletas perguntam se a placa de carbono "perde o efeito" com a quilometragem. Na realidade, o que perde resiliência primeiro é a espuma nitrogenada adjacente (PEBA/EVA supercrítico). Fizemos um teste no laboratório CoreMotiom com 15 pares entre 0km e 600km.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    likes_count: 89,
    comments_count: 14,
    comments: [
      {
        id: 'comm-3',
        author_name: 'Felipe Martins',
        content: 'Muito esclarecedor! É por isso que o SmartScan do app ajuda tanto a cotar o preço justo de tênis usados.',
        created_at: '2026-08-31T15:10:00Z',
      }
    ],
    created_at: '2026-08-31T08:15:00Z',
  }
];

export const INITIAL_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'A Evolução dos Super Tênis: Novos Polímeros Nitrogenados Reduzem Custo Energético em até 5.2%',
    summary: 'Estudo biomecânico com 120 atletas comprova que a combinação de placas côncavas e matrizes celulares supercríticas acelera a recuperação pós-prova.',
    content: 'O avanço na engenharia de calçados de competição continua quebrando paradigmas no atletismo internacional. A nova geração de entressolas utiliza processos de infusão de nitrogênio em temperaturas criogênicas, aumentando a densidade elástica sem elevar o peso final do calçado. No CoreMotiom, o laboratório de performance acompanha cada lançamento para validar tecnicamente as especificações anunciadas pelas fabricantes.',
    category: 'Tecnologia Esportiva',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    published_at: '2026-08-30T14:00:00Z',
    read_time: '4 min de leitura',
    author: 'Redação CoreMotiom Tech',
  },
  {
    id: 'news-2',
    title: 'Mercado de Equipamentos Esportivos C2C cresce 42% impulsionado por sustentabilidade e economia circular',
    summary: 'Atletas de ponta e praticantes amadores adotam o ecossistema de revenda verificada de peças técnicas e componentes esportivos.',
    content: 'A venda direta de equipamentos esportivos entre praticantes encontrou um novo patamar de segurança com plataformas especializadas. O processo de autenticação visual, verificação de lojistas oficiais e garantia de entrega criam um ciclo sustentável onde equipamentos de alta qualidade têm sua vida útil maximizada.',
    category: 'Mercado & Negócios',
    image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    published_at: '2026-08-28T09:30:00Z',
    read_time: '3 min de leitura',
    author: 'Redação CoreMotiom Business',
  },
  {
    id: 'news-3',
    title: 'Nutrição Intra-Treino: Como a ingestão de 90g a 120g de carboidratos/hora transforma o desempenho no endurance',
    summary: 'Diretrizes internacionais de fisiologia destacam o treinamento do trato gastrointestinal para suportar cargas elevadas de glicose e frutose.',
    content: 'Durante décadas a recomendação padrão de carboidratos em exercícios de longa duração foi limitada a 60g por hora. Com a introdução da proporção 1:0.8 de glicose e frutose, os transportadores intestinais SGLT1 e GLUT5 atuam em sinergia, permitindo oxigenação sustentada sem episódios de hipoglicemia de rebote.',
    category: 'Fisiologia & Treino',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    published_at: '2026-08-26T16:20:00Z',
    read_time: '5 min de leitura',
    author: 'Dr. Lucas Silveira, Fisiologia do Exercício',
  },
];
