import pg from "pg";
import fs from "fs";
import crypto from "crypto";

// Deterministic UUID generator from slug
function getUuid(name) {
  const hash = crypto.createHash("md5").update("coremotiom-product-" + name).digest("hex");
  return [
    hash.substring(0, 8),
    hash.substring(8, 12),
    "4" + hash.substring(13, 16),
    "a" + hash.substring(17, 20),
    hash.substring(20, 32)
  ].join("-");
}

const products = [
  // --- Tênis Casuais & Streetwear Esportivo ---
  {
    id: getUuid("nike-air-force-1-07-white"),
    title: "Tênis Nike Air Force 1 '07 Branco Clássico",
    description: "O clássico do basquete e do streetwear mundial. Cabedal em couro legítimo branco imaculado com costuras reforçadas, perfurações no bico para respirabilidade, amortecimento Nike Air encapsulado para conforto prolongado e solado de borracha aderente com ponto de giro clássico.",
    price: 799.90,
    original_price: 899.90,
    category: "Calçados",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/nike-air-force-1.jpg", "/products/nike-air-force-1-front.jpg"],
    seller_id: null,
    seller_name: "Nike Flagship Store Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&q=80",
    store_id: "04ce38dd-7193-4e53-a2e0-1466f45d7f19",
    store_name: "Nike Flagship Store Brasil",
    is_verified_store: true,
    stock: 24,
    views: 1840,
    likes_count: 142,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 48).toISOString(),
    tags: ["Casual", "Streetwear", "Nike", "Air Force", "Couro", "Branco"],
    brand: "Nike",
    rating: 4.9,
    reviews_count: 318
  },
  {
    id: getUuid("adidas-samba-og-black-white"),
    title: "Tênis Adidas Samba OG Preto & Branco",
    description: "Nascido nos campos de futebol de salão e consagrado como o maior ícone urbano atual. Confeccionado em couro premium macio na cor preta, sobreposição em camurça T-toe na biqueira, as inconfundíveis 3 listras serrilhadas em couro branco e tradicional sola de borracha natural gum.",
    price: 699.90,
    original_price: 749.90,
    category: "Calçados",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/adidas-samba-og.jpg", "/products/adidas-samba-og-side.jpg"],
    seller_id: null,
    seller_name: "Adidas Originals & Adizero Lab",
    seller_avatar: "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=120&q=80",
    store_id: "d2b5d694-85ae-41c8-bc49-fdcc25ddd9e3",
    store_name: "Adidas Originals & Adizero Lab",
    is_verified_store: true,
    stock: 18,
    views: 1520,
    likes_count: 119,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 44).toISOString(),
    tags: ["Casual", "Streetwear", "Adidas", "Samba", "Originals", "Camurça"],
    brand: "Adidas",
    rating: 4.9,
    reviews_count: 245
  },
  {
    id: getUuid("vans-old-skool-black-white"),
    title: "Tênis Vans Old Skool Core Preto & Branco",
    description: "O lendário modelo de skate com a primeira aparição da icônica sidestripe da Vans. Cabedal de alta durabilidade em lona e camurça preta resistente ao atrito, biqueiras reforçadas para suportar o uso diário, colarinho acolchoado para apoio e a original sola waffle de borracha.",
    price: 399.90,
    original_price: 449.90,
    category: "Calçados",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/vans-old-skool-1.jpg", "/products/vans-old-skool-2.jpg"],
    seller_id: null,
    seller_name: "Centauro Pro & Casual",
    seller_avatar: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=120&q=80",
    store_id: "2bb0caf3-b803-47b8-be03-9d6c5eba2684",
    store_name: "Centauro Pro & Casual",
    is_verified_store: true,
    stock: 35,
    views: 1210,
    likes_count: 88,
    location: "Barueri - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 40).toISOString(),
    tags: ["Casual", "Skate", "Vans", "Old Skool", "Lona", "Waffle"],
    brand: "Vans",
    rating: 4.8,
    reviews_count: 194
  },
  {
    id: getUuid("puma-suede-classic-xxi-black"),
    title: "Tênis Puma Suede Classic XXI Preto & Branco",
    description: "Referência histórica no breakdance e na cultura hip-hop desde 1968. Cabedal 100% em camurça premium macia na tonalidade preta profunda, palmilha confortável acolchoada, detalhe lateral Formstrip Puma em branco e entressola texturizada de borracha durável.",
    price: 429.90,
    original_price: 499.90,
    category: "Calçados",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/puma-suede-1.jpg", "/products/puma-suede-2.jpg"],
    seller_id: null,
    seller_name: "Puma Running & Sportstyle Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=120&q=80",
    store_id: "e1b07986-63fc-4cc6-9ae1-bfc62836360f",
    store_name: "Puma Running & Sportstyle Brasil",
    is_verified_store: true,
    stock: 15,
    views: 940,
    likes_count: 67,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 36).toISOString(),
    tags: ["Casual", "Streetwear", "Puma", "Suede", "Camurça", "Clássico"],
    brand: "Puma",
    rating: 4.8,
    reviews_count: 112
  },
  {
    id: getUuid("asics-japan-s-white-navy"),
    title: "Tênis Asics Japan S Branco & Marinho",
    description: "Inspirado na herança das quadras de basquete de 1981 da Asics. Silhueta de cano baixo repaginada para o dia a dia casual com cabedal macio em couro sintético limpo, listras tigradas Asics contrastantes e entressola cupsole modificada para excelente leveza.",
    price: 329.90,
    original_price: 449.90,
    category: "Calçados",
    sport: "Casual",
    condition: "seminovo",
    product_type: "c2c",
    images: ["/products/asics-japan-s-1.jpg", "/products/asics-japan-s-2.jpg"],
    seller_id: null,
    seller_name: "Lucas 'Sprint' Mendes",
    seller_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80",
    store_id: null,
    store_name: null,
    is_verified_store: false,
    stock: 1,
    views: 680,
    likes_count: 43,
    location: "Campinas - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 32).toISOString(),
    tags: ["Casual", "Basquete Retrô", "Asics", "Japan S", "Couro", "Seminovo"],
    brand: "Asics",
    rating: 4.9,
    reviews_count: 28
  },

  // --- Tênis de Treino / Corrida Popular ---
  {
    id: getUuid("nike-pegasus-40-black-white"),
    title: "Tênis Nike Air Zoom Pegasus 40 Preto & Branco",
    description: "O companheiro de treinos diários mais confiável do mundo esportivo. Conta com duas unidades Zoom Air (antepé e calcanhar) associadas à entressola em espuma Nike React para amortecimento responsivo e elástico. Cabedal de camada única em engineered mesh com ajuste anatômico no médiopé.",
    price: 699.90,
    original_price: 899.90,
    category: "Calçados",
    sport: "Corrida",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/nike-pegasus-1.jpg", "/products/nike-pegasus-2.jpg"],
    seller_id: null,
    seller_name: "Nike Flagship Store Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&q=80",
    store_id: "04ce38dd-7193-4e53-a2e0-1466f45d7f19",
    store_name: "Nike Flagship Store Brasil",
    is_verified_store: true,
    stock: 22,
    views: 2130,
    likes_count: 178,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 30).toISOString(),
    tags: ["Corrida", "Treino Diário", "Nike", "Pegasus 40", "Zoom Air", "Amortecimento"],
    brand: "Nike",
    rating: 4.9,
    reviews_count: 420
  },
  {
    id: getUuid("olympikus-corre-3-graphite-orange"),
    title: "Tênis Olympikus Corre 3 Grafite & Laranja",
    description: "O tênis de corrida 100% desenvolvido e produzido no Brasil mais aclamado pelos corredores. Pesa apenas 210g com tecnologia Oxitec em monofilamento que não absorve água, entressola Eleva Pro com máxima impulsão e durabilidade, e sola Gripper antiderrapante com borracha compacta de alta tração.",
    price: 449.90,
    original_price: 499.90,
    category: "Calçados",
    sport: "Corrida",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/olympikus-corre-3.jpg", "/products/olympikus-corre-3-sole.jpg"],
    seller_id: null,
    seller_name: "Olympikus Flagship Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=120&q=80",
    store_id: "aab65940-3d81-4734-b72a-8d1d5dc5bda8",
    store_name: "Olympikus Flagship Brasil",
    is_verified_store: true,
    stock: 40,
    views: 3100,
    likes_count: 265,
    location: "Dois Irmãos - RS",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 28).toISOString(),
    tags: ["Corrida", "Treino", "Olympikus", "Corre 3", "Eleva Pro", "Oxitec", "Nacional"],
    brand: "Olympikus",
    rating: 4.9,
    reviews_count: 512
  },
  {
    id: getUuid("asics-gel-nimbus-26-navy"),
    title: "Tênis Asics Gel-Nimbus 26 Azul Marinho & Branco",
    description: "A mais alta expressão de amortecimento e conforto para rodagens longas e maratonas. Incorpora a tecnologia PureGEL no calcanhar que é 65% mais macia que o gel tradicional, entressola FF BLAST PLUS ECO super responsiva e cabedal em malha macia engineered knit de ajuste envolvente.",
    price: 1199.90,
    original_price: 1299.90,
    category: "Calçados",
    sport: "Corrida",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/asics-gel-nimbus-1.jpg", "/products/asics-gel-nimbus-2.jpg"],
    seller_id: null,
    seller_name: "Asics Flagship Store Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=120&q=80",
    store_id: "6ccdde63-cd6d-4ca4-a12e-c1b8c0f659e6",
    store_name: "Asics Flagship Store Brasil",
    is_verified_store: true,
    stock: 14,
    views: 1670,
    likes_count: 134,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 26).toISOString(),
    tags: ["Corrida", "Amortecimento Máximo", "Asics", "Nimbus 26", "PureGEL", "Longão"],
    brand: "Asics",
    rating: 5.0,
    reviews_count: 198
  },
  {
    id: getUuid("adidas-ultraboost-light-black"),
    title: "Tênis Adidas Ultraboost Light Preto Carbono",
    description: "Equipado com a nova geração da espuma Light BOOST, 30% mais leve que o Boost tradicional para retorno inesgotável de energia a cada passada. Cabedal PRIMEKNIT+ que abraça os pés com precisão cirúrgica e solado Continental com aderência extrema em piso seco ou molhado.",
    price: 599.90,
    original_price: 1199.90,
    category: "Calçados",
    sport: "Corrida",
    condition: "seminovo",
    product_type: "c2c",
    images: ["/products/adidas-ultraboost-1.jpg", "/products/adidas-ultraboost-2.jpg"],
    seller_id: null,
    seller_name: "Marina Costa (Maratonista RJ)",
    seller_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80",
    store_id: null,
    store_name: null,
    is_verified_store: false,
    stock: 1,
    views: 1120,
    likes_count: 94,
    location: "Rio de Janeiro - RJ",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 24).toISOString(),
    tags: ["Corrida", "Treino", "Adidas", "Ultraboost", "Primeknit", "Light Boost"],
    brand: "Adidas",
    rating: 4.9,
    reviews_count: 36
  },

  // --- Roupas & Vestuário Casual/Fitness ---
  {
    id: getUuid("nike-windbreaker-black"),
    title: "Jaqueta Corta-Vento Esportiva Repelente à Água Preta",
    description: "Jaqueta corta-vento ultraleve confeccionada em tecido ripstop resistente a rajadas de vento e respingos de chuva fina. Possui capuz ergonômico com cordão de ajuste, fechamento frontal por zíper reforçado, punhos elásticos ajustáveis e detalhes refletivos discretos de segurança.",
    price: 299.90,
    original_price: 379.90,
    category: "Vestuário",
    sport: "Corrida",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/jaqueta-corta-vento.jpg", "/products/jaqueta-corta-vento-back.jpg"],
    seller_id: null,
    seller_name: "Track&Field Lifestyle & Run",
    seller_avatar: "https://images.unsplash.com/photo-1544441893-675973e31985?w=120&q=80",
    store_id: "15eb75a0-b53a-4b8a-9ce1-b4bff031e750",
    store_name: "Track&Field Lifestyle & Run",
    is_verified_store: true,
    stock: 30,
    views: 1450,
    likes_count: 105,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 22).toISOString(),
    tags: ["Vestuário", "Corta-Vento", "Jaqueta", "Repelente à Água", "Corrida", "Capuz"],
    brand: "Nike",
    rating: 4.8,
    reviews_count: 154
  },
  {
    id: getUuid("nike-dry-fit-shirt-black"),
    title: "Camiseta Dry-Fit Básica de Treino Masculina Preta",
    description: "A peça essencial para academia, esteira ou treinos ao ar livre. Tecido em microfibra 100% poliéster tecnológico com gerenciamento térmico Dri-FIT que dispersa a umidade e evapora o suor com agilidade. Costuras planas antifricção que evitam assaduras na pele.",
    price: 119.90,
    original_price: 149.90,
    category: "Vestuário",
    sport: "Treino",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/dry-fit-shirt-1.jpg", "/products/dry-fit-shirt-2.jpg"],
    seller_id: null,
    seller_name: "Centauro Pro & Casual",
    seller_avatar: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=120&q=80",
    store_id: "2bb0caf3-b803-47b8-be03-9d6c5eba2684",
    store_name: "Centauro Pro & Casual",
    is_verified_store: true,
    stock: 50,
    views: 1980,
    likes_count: 162,
    location: "Barueri - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 20).toISOString(),
    tags: ["Vestuário", "Camiseta", "Dry-Fit", "Treino", "Academia", "Respirável"],
    brand: "Nike",
    rating: 4.9,
    reviews_count: 310
  },
  {
    id: getUuid("adidas-hoodie-grey-heather"),
    title: "Moletom Esportivo com Capuz e Bolso Canguru Cinza Mescla",
    description: "Moletom unissex flanelado de alto padrão em mescla de algodão sustentável e poliéster térmico. Interior macio que retém o calor nos dias frios, capuz duplo forrado com cordão regulador, bolso canguru frontal amplo e barras caneladas em ribana resistente.",
    price: 279.90,
    original_price: 349.90,
    category: "Vestuário",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/moletom-hoodie-1.jpg", "/products/moletom-hoodie-2.jpg"],
    seller_id: null,
    seller_name: "Adidas Originals & Adizero Lab",
    seller_avatar: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=120&q=80",
    store_id: "d2b5d694-85ae-41c8-bc49-fdcc25ddd9e3",
    store_name: "Adidas Originals & Adizero Lab",
    is_verified_store: true,
    stock: 25,
    views: 1330,
    likes_count: 98,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 18).toISOString(),
    tags: ["Vestuário", "Moletom", "Capuz", "Canguru", "Casual", "Algodão"],
    brand: "Adidas",
    rating: 4.9,
    reviews_count: 142
  },
  {
    id: getUuid("under-armour-compression-shorts-black"),
    title: "Bermuda de Compressão com Bolso Lateral para Celular",
    description: "Desenvolvida para alta sustentação muscular e prevenção de fadiga em tiros e treinos intensos. Tecido anatômico com compressão graduada, costuras ergonômicas que não sobem na coxa e bolso lateral profundo que mantém o smartphone 100% estável sem chacoalhar durante a corrida.",
    price: 149.90,
    original_price: 189.90,
    category: "Vestuário",
    sport: "Treino",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/bermuda-compressao-1.jpg", "/products/bermuda-compressao-2.jpg"],
    seller_id: null,
    seller_name: "Under Armour Brasil",
    seller_avatar: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=120&q=80",
    store_id: "b94ec08d-da96-4b1c-a424-93fa632cfd14",
    store_name: "Under Armour Brasil",
    is_verified_store: true,
    stock: 28,
    views: 990,
    likes_count: 81,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 16).toISOString(),
    tags: ["Vestuário", "Bermuda", "Compressão", "Treino", "Corrida", "Bolso Celular"],
    brand: "Under Armour",
    rating: 4.8,
    reviews_count: 165
  },
  {
    id: getUuid("nike-brazil-jersey-2024-yellow"),
    title: "Camisa Oficial de Futebol Torcedor Brasil 2024 Amarela",
    description: "Manto sagrado da Seleção Brasileira de Futebol modelo torcedor oficial. Tecido tecnológico respirável com tecnologia de microperfurações para excelente ventilação nos dias de calor, escudo bordado no peito em alta definição, gola V canelada e padrão texturizado sutil.",
    price: 349.90,
    original_price: 399.90,
    category: "Vestuário",
    sport: "Futebol",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/camisa-futebol-1.jpg", "/products/camisa-futebol-2.jpg"],
    seller_id: null,
    seller_name: "Centauro Pro & Casual",
    seller_avatar: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=120&q=80",
    store_id: "2bb0caf3-b803-47b8-be03-9d6c5eba2684",
    store_name: "Centauro Pro & Casual",
    is_verified_store: true,
    stock: 35,
    views: 2450,
    likes_count: 215,
    location: "Barueri - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 14).toISOString(),
    tags: ["Vestuário", "Camisa de Time", "Futebol", "Brasil", "Seleção", "Oficial"],
    brand: "Nike",
    rating: 4.9,
    reviews_count: 380
  },

  // --- Acessórios do Dia a Dia ---
  {
    id: getUuid("nike-sports-backpack-waterproof-28l"),
    title: "Mochila Esportiva Resistente à Água 28L com Porta-Notebook Preta",
    description: "A mochila definitiva para quem sai do trabalho direto para os treinos. Capacidade de 28 litros com tecido de poliéster 600D resistente à água, compartimento independente acolchoado para notebook de até 15.6\", bolso inferior ventilado para calçados e alças de ombro ergonômicas com tecido mesh respirável.",
    price: 299.90,
    original_price: 379.90,
    category: "Acessórios",
    sport: "Casual",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/mochila-esportiva.jpg", "/products/mochila-esportiva-straps.jpg"],
    seller_id: null,
    seller_name: "Decathlon Flagship Morumbi",
    seller_avatar: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=120&q=80",
    store_id: "c642f3e6-253f-492a-b898-86a475101b04",
    store_name: "Decathlon Flagship Morumbi",
    is_verified_store: true,
    stock: 40,
    views: 1870,
    likes_count: 145,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 12).toISOString(),
    tags: ["Acessórios", "Mochila", "Resistente à Água", "Notebook", "Treino", "Dia a Dia"],
    brand: "Nike",
    rating: 4.9,
    reviews_count: 220
  },
  {
    id: getUuid("nike-aerobill-cap-black"),
    title: "Boné Esportivo Aba Curva Dry Aerobill Preto",
    description: "Boné técnico construído com tecnologia Nike AeroBill que combina respirabilidade avançada com conforto antissuor. Perfurações cortadas a laser nas laterais e traseira aumentam a circulação do ar nos treinos sob sol intenso. Fecho traseiro ajustável por fita aderente.",
    price: 129.90,
    original_price: 159.90,
    category: "Acessórios",
    sport: "Corrida",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/bone-aerobill-1.jpg", "/products/bone-aerobill-2.jpg"],
    seller_id: null,
    seller_name: "Top Run Curitiba",
    seller_avatar: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=120&q=80",
    store_id: "10acfac9-d361-4d65-ad13-175cf8a8997a",
    store_name: "Top Run Curitiba",
    is_verified_store: true,
    stock: 45,
    views: 1110,
    likes_count: 92,
    location: "Curitiba - PR",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 10).toISOString(),
    tags: ["Acessórios", "Boné", "Aba Curva", "Dry", "Aerobill", "Proteção Solar"],
    brand: "Nike",
    rating: 4.8,
    reviews_count: 180
  },
  {
    id: getUuid("xiaomi-smartband-fitness-black"),
    title: "Smartband Relógio Inteligente Fitness Monitor Cardíaco & Sono",
    description: "Pulseira inteligente com tela colorida AMOLED de 1.62 polegadas de alta resolução com brilho ajustável automático. Monitora batimentos cardíacos 24h por segundo, saturação de oxigênio no sangue (SpO2), índice de estresse, sono REM e suporta mais de 150 modos esportivos com bateria que dura até 16 dias.",
    price: 249.90,
    original_price: 319.90,
    category: "Acessórios",
    sport: "Treino",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/smartband-fitness-1.jpg", "/products/smartband-fitness-2.jpg"],
    seller_id: null,
    seller_name: "Pulse Peak Tech",
    seller_avatar: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=120&q=80",
    store_id: "a60931df-e184-48bf-bdfd-a4970a3f92e4",
    store_name: "Pulse Peak Tech",
    is_verified_store: true,
    stock: 30,
    views: 2280,
    likes_count: 189,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 8).toISOString(),
    tags: ["Acessórios", "Tecnologia", "Smartband", "Monitor Cardíaco", "Sono", "Fitness"],
    brand: "Xiaomi",
    rating: 4.9,
    reviews_count: 275
  },
  {
    id: getUuid("stanley-water-bottle-inox-750ml"),
    title: "Garrafa Térmica Esportiva em Inox 750ml com Tampa Bico Rápido",
    description: "Garrafa térmica com isolamento a vácuo em parede dupla de aço inoxidável 18/8. Mantém a bebida gelada por até 24 horas consecutivas (ou com gelo por 36h). Conta com tampa Flip-Straw de canudo retrátil antivazamento acionável com uma mão e alça rígida para transporte na academia.",
    price: 189.90,
    original_price: 239.90,
    category: "Acessórios",
    sport: "Treino",
    condition: "novo",
    product_type: "b2c",
    images: ["/products/garrafa-termica-1.jpg", "/products/garrafa-termica-2.jpg"],
    seller_id: null,
    seller_name: "Track&Field Lifestyle & Run",
    seller_avatar: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=120&q=80",
    store_id: "15eb75a0-b53a-4b8a-9ce1-b4bff031e750",
    store_name: "Track&Field Lifestyle & Run",
    is_verified_store: true,
    stock: 35,
    views: 1420,
    likes_count: 116,
    location: "São Paulo - SP",
    shipping_available: true,
    status: "active",
    created_at: new Date(Date.now() - 1000 * 3600 * 6).toISOString(),
    tags: ["Acessórios", "Hidratação", "Garrafa Térmica", "Inox", "Bico Rápido", "Isolamento"],
    brand: "Stanley",
    rating: 4.9,
    reviews_count: 195
  }
];

async function run() {
  const client = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
  await client.connect();

  console.log("Replacing all products in PostgreSQL database with valid UUIDs...");
  await client.query("BEGIN");
  await client.query("DELETE FROM public.products");

  for (const p of products) {
    await client.query(`
      INSERT INTO public.products (
        id, title, description, price, original_price, category, sport,
        condition, product_type, images, seller_id, seller_name, seller_avatar,
        store_id, store_name, is_verified_store, stock, views, likes_count,
        location, shipping_available, status, brand, tags, created_at, updated_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13,
        $14, $15, $16, $17, $18, $19,
        $20, $21, $22, $23, $24, $25, $26
      )
    `, [
      p.id,
      p.title,
      p.description,
      p.price,
      p.original_price,
      p.category,
      p.sport,
      p.condition,
      p.product_type,
      p.images,
      p.seller_id,
      p.seller_name,
      p.seller_avatar,
      p.store_id || null,
      p.store_name || null,
      p.is_verified_store,
      p.stock,
      p.views,
      p.likes_count,
      p.location,
      p.shipping_available,
      p.status,
      p.brand,
      p.tags,
      p.created_at,
      new Date().toISOString()
    ]);
  }
  await client.query("COMMIT");

  const countRes = await client.query("SELECT COUNT(*) FROM public.products");
  console.log("SUCCESS! Total products in PostgreSQL database:", countRes.rows[0].count);

  // Update lib/initial-data.ts
  let initialDataContent = fs.readFileSync("lib/initial-data.ts", "utf-8");
  const pStart = initialDataContent.indexOf("export const INITIAL_PRODUCTS: Product[] = [");
  const pEnd = initialDataContent.indexOf("export const INITIAL_COACHES: Coach[] = [");

  if (pStart !== -1 && pEnd !== -1) {
    const tsCode = "export const INITIAL_PRODUCTS: Product[] = " + JSON.stringify(products, null, 2) + ";\n\n";
    initialDataContent = initialDataContent.slice(0, pStart) + tsCode + initialDataContent.slice(pEnd);
    fs.writeFileSync("lib/initial-data.ts", initialDataContent, "utf-8");
    console.log("Successfully updated lib/initial-data.ts with all", products.length, "curated products!");
  } else {
    console.error("Could not find delimiters in lib/initial-data.ts");
  }

  await client.end();
}

run().catch((e) => {
  console.error("Migration error:", e);
  process.exit(1);
});
